import { IconMicroscope, IconAI, IconLeaf, IconDNA } from "./Icons";

type Category = "全部" | "科学" | "学习项目" | "AI工具";

export const works = [
  {
    id: 1, slug: "gene-expression", category: "科学" as Category,
    icon: <IconMicroscope size={36} color="var(--cherry-blue)" />,
    title: "基因表达可视化",
    desc: "拖拽 TF、RNA 聚合酶和核糖体，观察 mRNA 端点、核糖体读取、多肽链和 5 道即时小测。",
    task: "把 TF 调低再打开 RNA 聚合酶，观察 mRNA 生成变少、核糖体读取减少、蛋白链产量下降。",
    starter: "先把 RNA 聚合酶打开，再拖动时间滑块，看 mRNA 曲线如何带出核糖体和多肽链。",
    success: "能说清 DNA 信息如何转成 mRNA、核糖体如何读密码子，并用读数解释蛋白链为什么变多或变少。",
    href: "/works/gene-expression",
    updated: "2026-06-04",
    tags: ["生物", "可视化", "交互"],
    outputs: ["表达读数", "过程记录", "即时小测"],
    path: ["调节分子", "观察过程", "复制记录"],
    action: "启动仿真",
    color: "var(--cherry-blue-light)", border: "var(--cherry-blue)", rotate: "-1.5deg",
  },
  {
    id: 3, slug: "research-prompt-kit", category: "AI工具" as Category,
    icon: <IconAI size={36} color="var(--cherry-blue)" />,
    title: "科研 Agent 工作台",
    desc: "选择科研任务和工作模式，把材料组织成模型指令、证据边界、引用核查、质控清单和汇报任务包。",
    task: "粘贴一段摘要或图注，运行本地预览，得到任务路由、缺失信息、引用核查和可复制 API JSON。",
    starter: "先载入读论文练习，运行本地预览，看系统如何拆出证据候选和缺失字段。",
    success: "能把一段科研材料整理成任务路由、证据边界、引用核查和下一步核查清单，并知道哪些内容不能让模型直接定论。",
    href: "/works/research-prompt-kit",
    updated: "2026-06-04",
    tags: ["AI", "Agent", "科研"],
    outputs: ["任务路由", "引用核查", "报告框架"],
    path: ["粘贴材料", "核查来源", "复核报告"],
    action: "进入工作台",
    color: "var(--cherry-peach-light)", border: "var(--cherry-peach)", rotate: "-0.8deg",
  },
  {
    id: 4, slug: "plant-evolution-stories", category: "学习项目" as Category,
    icon: <IconLeaf size={36} color="var(--cherry-sage)" />,
    title: "植物演化时间轴",
    desc: "演化时间轴串联关键创新、证据、自测问题、作答提示和延伸练习。",
    task: "选择一个演化阶段，读证据卡，再用自测问题判断这项创新解决了什么生存压力。",
    starter: "先点种子阶段，比较孢子和种子各自解决了什么传播与保护问题。",
    success: "能按时间顺序解释至少三个植物关键创新，并用证据说出它们各自解决的生存压力。",
    href: "/works/plant-evolution-stories",
    updated: "2026-06-04",
    tags: ["植物学", "演化证据", "时间轴"],
    outputs: ["学习卡", "阶段比较", "证据判读"],
    path: ["选择阶段", "判读证据", "完成练习"],
    action: "探索时间轴",
    color: "var(--cherry-sage-light)", border: "var(--cherry-sage)", rotate: "1.8deg",
  },
  {
    id: 5, slug: "concept-explainer", category: "AI工具" as Category,
    icon: <IconAI size={36} color="#7B6CC4" />,
    title: "概念解释生成器",
    desc: "输入任意概念或选择样例，生成自测问题、类比、机制步骤、可视化流程、迁移练习和即时小测。",
    task: "输入一个卡住的概念，先看诊断边界，再生成可复制的学习卡和即时小测。",
    starter: "先输入光合作用或生态位，按诊断、类比、机制、练习四步检查自己是否真懂。",
    success: "能产出一张包含定义、机制、例子、边界和自测题的学习卡，并标出仍需查资料的部分。",
    href: "/works/concept-explainer",
    updated: "2026-06-04",
    tags: ["AI", "学习卡", "工具"],
    outputs: ["学习卡", "可视化流程", "即时小测"],
    path: ["输入概念", "看诊断边界", "生成学习卡"],
    action: "生成学习卡",
    color: "#EDE9F5", border: "#B5AEDD", rotate: "-1.2deg",
  },
  {
    id: 6, slug: "crispr-interactive", category: "科学" as Category,
    icon: <IconDNA size={36} color1="var(--cherry-red)" color2="var(--cherry-blue)" />,
    title: "CRISPR 编辑模拟器",
    desc: "操作 guide RNA、Cas 蛋白和修复结果，查看匹配评分、编辑判定、风险核查和模拟报告。",
    task: "找出 PAM，修改 guide RNA 碱基，比较匹配评分如何影响切割和修复结果。",
    starter: "先选高匹配敲除场景，再切到错配比较，看判定为什么从推荐继续变成谨慎使用。",
    success: "能根据 PAM、guide 匹配评分和修复结果判断一次编辑是否值得继续，并写出风险理由。",
    href: "/works/crispr-interactive",
    updated: "2026-06-04",
    tags: ["基因编辑", "互动", "CRISPR"],
    outputs: ["guide 判定", "风险核查", "模拟报告"],
    path: ["找 PAM", "判 guide", "核查风险"],
    action: "运行编辑",
    color: "var(--cherry-peach-light)", border: "var(--cherry-red)", rotate: "0.5deg",
  },
];
